### ISSUE TITLE
Feature request: wrap lines in Args and Ret panes.

### ISSUE THREAD

**Issue by agzam** [flow-storm/flow-storm-debugger#102]
Would be nice to have arguments and return value panes to wrap around (optionally or automatically). 

![image](https://github.com/flow-storm/flow-storm-debugger/assets/1091022/1176c963-e0e4-47dc-8c9f-f104c9b7587a)

**Comment by jpmonettas** [comment]
Makes sense. Should be pretty easy to implement since that is a TextArea which already contains a setWrapText file:///home/jmonetta/docs/javafx-18.0.2-javadoc/javafx.controls/javafx/scene/control/TextArea.html#setWrapText(boolean)

The thing is that I'm not sure if it is a good idea to always have it enable, probably not. So it would probably needs a checkbox somewhere.

**Comment by MayaBrito** [comment]
Hello, can I take this issue? 🐱 
@jpmonettas

**Comment by jpmonettas** [comment]
Hi @MayaBrito ! Sure, let me know if you have any questions here or on #flow-storm @ Clojurians Slack
