### ISSUE TITLE
GUI keeps switching to "taps" tab by itself

### ISSUE THREAD

**Issue by licht1stein** [flow-storm/flow-storm-debugger#117]
Just some very annoying UI behavior. Every 10 seconds or so GUI just switches to taps by itself.

**Comment by jpmonettas** [comment]
Hi @licht1stein! The UI should only change to the Taps automatically when you get a new tap. So it looks to me like you have a thread tapping something every 10 seconds?

**Comment by licht1stein** [comment]
Can this be disabled? I would like to be able to control the UI myself :)

**Comment by licht1stein** [comment]
I mean, if you say we should be able to inspect a running program durint
development, this means it might also have taps :)

**Comment by jpmonettas** [comment]
Yeah that is true. Currently the UI will switch to the Taps tab every time you receive a tap>, but maybe we should remove that automatic switching, which is annoying on those situations.
I never run into that, since I never had code constantly tapping something.  
In the meantime you can disable flow-storm listening to taps by executing `(flow-storm.runtime.taps/remove-tap!)` on your repl.

**Comment by jpmonettas** [comment]
@licht1stein I just removed that behavior from master, so if you use the master version that should be fixed. I'll be releasing a new version soon.

**Comment by licht1stein** [comment]
Awesome, thank you so much!

**Comment by licht1stein** [comment]
I tap> all requests and responses to inspect them in Portal when developing, it renders them very well

**Comment by jpmonettas** [comment]
Yeah, that is handy. Just in case you aren't aware, you don't need to tap them with flow-storm. You can select them from the recordings, and inspect them in the flow-storm inspector when you need, or click the `tap` button next to any value and it will re-tap it if you want to send it to portal in case you like that inspector better.

**Comment by licht1stein** [comment]
I tap them from ring-middleware that is only active in development. I don't
quite understand what you mean.

**Comment by jpmonettas** [comment]
@licht1stein What I mean is that when using FlowStorm you don't need to tap anything, since you can record everything with a click.
So, what I do, instead of constantly tapping my requests in a middleware, whenever I need to look at requests I just turn recording on and then I look at them in the tree or the functions list. Which not only allows to see the request maps but also follow the requests through the application, stepping the handlers, etc. 

By the way, version `3.9.1` already includes this issue change.
