### ISSUE TITLE
Add some differences for frames displaying functions currently in stack

### ISSUE THREAD

**Issue by velios** [flow-storm/flow-storm-debugger#131]
<img width="1471" alt="image" src="https://github.com/flow-storm/flow-storm-debugger/assets/9293462/382c0ce2-8c6c-40ef-a469-8ed45b8a13d7">

The frames displaying the contents of the functions that I have already viewed remain and there is no emphasis on which of the displayed frames are now in the stack. Some kind of insignia. A frame around the frames, some kind of icon or mode switch between showing only frames from the frame/all frames (as now).

**Comment by jpmonettas** [comment]
So the frames showing on the stack aren't related in any way to the visited ones. Everything on the right is related to the current position.
The previous visited forms remain there just for reference.
Does it make sense?

**Comment by velios** [comment]
I think this is convenient so that when analyzing the code, you can understand which functions from the entire list of frames are currently on the stack. Just to clearly see where I came from to the current function. 

In the example the functions `real-world-system` and `system-map` do not allow me to quickly understand that I came to  current fn `start-sytem` from the function `-main`. You can figure it out, but it’s not accessible for a quick visual assessment.

**Comment by jpmonettas** [comment]
Sorry I'm not sure I follow. The way it works that the stack shows you the current call-stack, should be the same as an stacktrace on a exception. It is not related to the history of your stepping.

You should read the satck on the right as I'm currently on `start-system` which was called by `main-` which was called by 'eval`.
`real-world-system` is not in your stack anymore since it already finished executing when you arrived to `start-system`. 

> do not allow me to quickly understand that I came to current fn start-sytem from the function -main
that is what the stack on the right is for.

The forms showing on the code panel has no order, you can even go back an forth between them in any order. The only reason we are not showing only one at the time is because sometime you want to be able to read the things you stepped earlier.

Make sense?
