### ISSUE TITLE
The loop menu feels janky when there are too many iterations

### ISSUE THREAD

**Issue by jpmonettas** [flow-storm/flow-storm-debugger#137]

**Comment by maxrothman** [comment]
I wonder if the most straightforward approach is to just treat loop iterations like recursive fn calls. That way users can use the same tools they already use to filter/navigate fn calls on loops too

**Comment by jpmonettas** [comment]
No, they aren't the same thing. Function calls are recorded in the timeline as `fn-call` and `fn-return` while loops aren't special in any way, they are just `expr-exec` recorded multiple times inside a fn body.
Also it would be super confusing to see functions calls on the tree and functions lists which aren't functions.

I think the way to go is to create a more powerful UI for navigating loops lazily, and provide some tools to move around that part of the timeline in a lazy manner.

**Comment by maxrothman** [comment]
I’m aware they’re not the same thing in the data model, I’m saying that from a user perspective, there’s not much difference between a loop and an internal tail-recursive fn. The UI already has tools for navigating (recursive) fns, so I’m wondering if thinking about loops in that way would yield a more cohesive user experience and avoid having to develop a similar but separate UI for loops.

**Comment by jpmonettas** [comment]
Can you elaborate a little bit more on how you would accomplish it from a UI perspective?

**Comment by maxrothman** [comment]
I don't have a completely firm idea of how it would look, but one approach might be to give loops some kind of name and include them in function lists. So just like a defn call is shown as `foo.bar/fname arg1 arg2 ...`, and a fn call is shown as `foo.bar/fn--12532 args` or `foo.bar/fname/fn--123143 args`, a loop could be shown as `foo.bar/fname/loop-123 arg1 arg2 ...`. `123` could be the line number, an arbitrary number, or some other way of disambiguating multiple loops in the same fn.

Another interesting question is: _where_ would you want to include loop iterations? I think the strongest argument would be for including them in the fn calls list in the flows tab, since that's currently where you can look through the list of all the calls to a fn. I think to be really useful though, that view would need some work: currently you can't inspect arguments, you can only view return values one at a time, there's no way to search in the arguments list or for a particular return value, and whenever you leave that view and return to it, all the selection highlights are gone so you can't see where the data currently being displayed came from. When needing to find a particular iteration, I found myself instead adding a print, searching the prints list, and using that to jump into the code.

I think a more useful UI would be one that supported the following user story:
- I'm debugging a fn and I arrive at a loop/call to recursive fn/repeated call to anonymous fn via map, etc... I know something bad happens in one of the calls/iterations, but I'm not sure which one.
- I'm able to easily jump to the list of calls. From there I can search for the call where the thing goes wrong.
- Once I've found the problematic call, I can quickly jump back into stepping at that frame.

In any case I think the next question that arises is, if loops appear in the fn calls list, is it more confusing for them to appear in the tree view as well or not? I'm not really sure, I think I'd have to try it out to be sure.

I think that's all the places in the UI that list fn calls? Please correct me if I missed any.

**Comment by jpmonettas** [comment]
Thanks for the detailed description of the problem.

I get your idea and how something like that would be helpful, but I still think that situations like that can be covered by specific loop tools, without the need to mix them with function calls, which raises all the other questions.

First I think moving around big loops by visual inspection doesn't make a lot of sense. So rendering a 10k loop in the functions list without any searching mechanism I don't think is going to help much.

I think the new power-steppers added in 3.10 can already be pretty helpful with moving around in loops, specially the `custom-same-coord` since you can select any expression inside the loop and then add a predicate. If the predicate is well choose then power-step-next should take you right there, or you can use it to step over all your iterations where lets say `(fn [v] (> (:user/age v) 42)` or whatever, or take me to the iteration where this value is nil, or the string contains some email, etc.

Does it make sense?

I still think the loop navigation can be improved, but I don't feel rendering them as functions is worth the trouble.

**Comment by maxrothman** [comment]
> First I think moving around big loops by visual inspection doesn't make a lot of sense. So rendering a 10k loop in the functions list without any searching mechanism I don't think is going to help much.

I 100% agree there has to be a searching mechanism, that's table stakes. Should there be a list as well though? I think it could be useful in certain situations, i.e. the same ones in which looking at recursive fn calls is occasionally useful.

> I think the new power-steppers added in 3.10 can already be pretty helpful with moving around in loops, specially the `custom-same-coord` since you can select any expression inside the loop and then add a predicate. If the predicate is well choose then power-step-next should take you right there, or you can use it to step over all your iterations where lets say `(fn [v] (> (:user/age v) 42)` or whatever, or take me to the iteration where this value is nil, or the string contains some email, etc.

The new power stepper features are definitely a huge improvement, though I think there's some situations where it's helpful to get a big-picture view, or when writing a custom predicate creates more cognitive overhead than just searching would.
 
> I still think the loop navigation can be improved, but I don't feel rendering them as functions is worth the trouble.

I think there are a couple of different questions here:
- Would it take more work to create new UI for loops or to push loops into existing UI?
- Would it be a better user experience to create new UI for loops or to push loops into existing UI?

The loops-as-fn-calls idea was just the first thing that came to mind for me, so I don't think it's the be-all-end-all of solutions. I think there are probably simple quick wins (like the power steppers) that could improve the experience with loops, but it's also a good idea to have the ideal solution in mind so you can steadily make progress towards it.

A quick-win approach might be to replace the existing UI list that renders when you click a loop with a scrollable list capped at a small number of items, and with a search box at the top. I think there's still room for improvement there though: I find that the floating list often gets in the way of the code I want to see, it'd be nice to have it render out of the way somewhere.

Here's another idea: I find the left-hand panel to be not particularly useful most of the time. i usually only have a small number of traces, and I switch between traces infrequently. Mostly I just pick one trace and then debug around. What if that space could be used for a panel that, when you click a fn call or are in a loop, shows you all the calls to that fn/loop iterations, and lets you search on the args/returns?

**Comment by jpmonettas** [comment]
I mostly agree with all you have said there. I think we should go first with improving the current loop menu with a scrollable window/pane with search. The problem with search is that it is slow, because you need to serialize the values to string and then search for a string inside, but there is code for doing this already.

I also agree that the threads list on the left is a lot of space that can be reused in some situations, so I agree we can experiment with that also.

**Comment by jpmonettas** [comment]
This was much improved (solved?) in 3.14.0 https://flow-storm.github.io/flow-storm-debugger/user_guide.html#_loops

**Comment by jpmonettas** [comment]
Hey, thanks @maxrothman for the ideas.

> When you click on any expression, a sidebar pops up that shows you all the values at that coordinate in the recorded flow.

This is interesting, not sure about the UI, but maybe adding a extra split with all the values. One problem is that it will then compete with the current loop system, which is faster and more "looking around" instead of show me everything.
Also I'm not sure about the UI/UX, since this panel will appear only on some expressions (inside loops with more than one iteration).

> I've noticed that people tend to have trouble knowing when to use the printer tool

I'm super curious about where is that info is coming from. Are you working on a team with multiple people using FlowStorm and you have seen them struggle? If that is the case I would love to have more feedback on what people find useful, confusing, etc

> I wonder if it could be terminology problem, what if they were called "watched forms" (or "watches", etc.) instead

I agree that Printer isn't the best name, the idea was to tell people "use this like println". I'm not sure about watches since I would prefer to reserve that  term for real time (not related to recording) atom watchers, which FlowStorm used to have. I think on normal debuggers the term watch makes more sense, since it is actively watching a memory location or the result of an expression.

> Maybe just adding a prints sidebar to the code view would help?

This we could try yeah, but we would have to fit the current UI there, which allows you to manage and enable/disable prints, if you have any ideas.

**Comment by maxrothman** [comment]
> Hey, thanks @maxrothman for the ideas.

My pleasure!
 
> > When you click on any expression, a sidebar pops up that shows you all the values at that coordinate in the recorded flow.
> 
> This is interesting, not sure about the UI, but maybe adding a extra split with all the values. One problem is that it will then compete with the current loop system, which is faster and more "looking around" instead of show me everything. Also I'm not sure about the UI/UX, since this panel will appear only on some expressions (inside loops with more than one iteration).
 
Ok, there are few things here so I'll address them one by one.

#### Where should the UI go?
The flows sidebar curently takes up a lot of space and I don't think it's necessary to have it be visible all the time. The functionality currently in that sidebar could be put in tabs or in another view somewhere. That would free up that sidebar for these new purposes.

#### This competes with the current loop system

I agree it does. My hope would be that this sidebar approach would do everything the current system does better. For example, to support the "looking around" workflow, it could highlight the current iteration you're on in that sidebar and auto-scroll to it (under the hood, it could start at the current frame and then search backwards and forwards, rather than starting at the beginning and searching to the end. Heck you could even have it be lazy so you don't have to load in all the values in one go.)

#### This panel would only appear in loops with more than one iteration

I'd suggest thinking of this panel more generally. Rather than just being a loop tool, it would be a value inspector for a selected coordinate. It would be useful in loops, but it would also be useful if a function is called multiple times, or in recursive functions, etc.

In general I'm thinking about this being a tool that lets you navigate between frames that contain a given coordinate, for the workflow where you don't know where the frame you're looking for falls in the timeline. Flow Storm already has many adjacent tools, but none quite like this one:
- Some stepping tools let you navigate forwards and backwards in time across different coordinates
- Other stepping tools let you navigate forwards and backwards in time at the same coordinate, but only show you one frame at a time, meaning you have to know _where_ the frame you're looking for is in time
- The function list lets you look across time and shows you many frames at a time, but only does so for function arguments and return values

A note: since this sidebar would show values across loop iterations and across function calls, it might be a good idea to have some way of showing which function call each item is from (e.g. for a function with a loop in it that's called multiple times, you want to be able to tell which loop iterations are from the same fn call).


> > I've noticed that people tend to have trouble knowing when to use the printer tool
> 
> I'm super curious about where is that info is coming from. Are you working on a team with multiple people using FlowStorm and you have seen them struggle? If that is the case I would love to have more feedback on what people find useful, confusing, etc

This is a super unscientific generalization from my own experiences and from watching the types of questions that are common in the slack channel. I've seen this one play out a few times:

- Asker: How do I do X?
- Answerer: You could do Y or Z, or use the print tool
- Asker: Oh right, the print tool

or

- Asker: How do I do X?
- Asker: Oh I guess I could use the print tool

My guess is that there a few things contributing to this:
- The print tool is in a tab away from the views people are usually in, so they forget it's there
- Multiple steps are required to set up a print, so it's not "easy"
- The word "print" evokes the idea of print debugging, which is not interactive like it is in Flow Storm. With normal print debugging, you can't time-travel to the frame where the line was printed, which is a pretty significant difference. This could induce a sort of "category error" where people are associating a workflow with the tool that's more limited than what it can really do.

That said, definitely take this with a grain of salt, I could be overgeneralizing my experience.

> > I wonder if it could be terminology problem, what if they were called "watched forms" (or "watches", etc.) instead
> 
> I agree that Printer isn't the best name, the idea was to tell people "use this like println". I'm not sure about watches since I would prefer to reserve that term for real time (not related to recording) atom watchers, which FlowStorm used to have. I think on normal debuggers the term watch makes more sense, since it is actively watching a memory location or the result of an expression.

Hm, I guess "naming things" is on that hard problems list for a reason :P 

Some more wall-sticking: if we imagine that the value inspector sidebar (where the flows sidebar is now) already existed, you wouldn't need prints for ad-hoc stuff (you'd just click the coordinate). When would you still use them? Maybe it would be more of a bookmark thing. 🤷 

> > Maybe just adding a prints sidebar to the code view would help?
> 
> This we could try yeah, but we would have to fit the current UI there, which allows you to manage and enable/disable prints, if you have any ideas.

If you didn't like the value inspector idea, I think I'd still replace the flows sidebar and split it, with the smaller top pane being for the list of prints and the lower larger pane being for the printed values. That said, I like the value inspector idea better, so I think it's worth thinking about that before going down this path.

**Comment by jpmonettas** [comment]
Ok, a lot of things going on here, let me try to address them separately : 

> The flows sidebar currently takes up a lot of space and I don't think it's necessary to have it be visible all the time. The functionality currently in that sidebar could be put in tabs or in another view somewhere.

I guess you are referring to the threads sidebar. I know this takes some space but I haven't found a better way yet, so open to ideas. It used to be on tabs, but there are many systems that use a lot of threads, so having them only on tabs doesn't work for those situations.

> My hope would be that this sidebar approach would do everything the current system does better. For example, to support the "looking around" workflow, it could highlight the current iteration you're on in that sidebar and auto-scroll to it 

I think that is an interesting idea to explore

> I'd suggest thinking of this panel more generally. Rather than just being a loop tool, it would be a value inspector for a selected coordinate. It would be useful in loops, but it would also be useful if a function is called multiple times, or in recursive functions, etc.

This is not hard to implement (I think) but will need some more controls as you pointed out after, because a lot of times you are interested in the local iterations. Clicking a expression in a loop and seeing  a bunch of entries some from your current loop mixed up with some from other instances of the same expression when this function was called in a completely different context I would say it is confusing to say the least.

Also the Printer can't be completely replaced by this since it allows you to add many prints, and see how they interleave. This new solution as it is defined so far would be single expression oriented.

Since there are a lot of ideas here (I really appreciate them) I think we would have to go in steps.

1. we probably need a new issue for this
2. we need to find space in the code window for this other list
3. we could start by putting a  printer like there for the current expression, auto-scrolling to the current one, only restricted to the current frame (I know it still generates confusion, but a frame is the span of all entries from fn-call to fn-return, we are calling each record a timeline entry, [see here](https://raw.githubusercontent.com/flow-storm/flow-storm-debugger/master/docs/timeline.svg) )

After those  we can think how to extend that tool further maybe to include iterations from other frames.

@maxrothman what do you think?

**Comment by jpmonettas** [comment]
@maxrothman Regarding the threads list I just remembered that we also have the threads controls there https://flow-storm.github.io/flow-storm-debugger/user_guide.html#_thread_breakpoints
